# Generated by Django 4.2.7 on 2026-03-12 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContractorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed total amount payable to contractor for this project', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='workforce.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_assignments', to='attendance.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'contractor')},
            },
        ),
    ]
