# Generated by Django 4.2.7 on 2026-03-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourerpayroll',
            name='period',
        ),
        migrations.AddField(
            model_name='labourerpayroll',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labourerpayroll',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
