# Generated by Django 4.2.7 on 2026-02-24 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Labourer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Wage per overtime hour', max_digits=10)),
                ('skill', models.CharField(blank=True, help_text='e.g. Mason, Carpenter', max_length=100)),
                ('id_number', models.CharField(blank=True, help_text='National ID / Employee ID', max_length=50)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labourers', to='workforce.contractor')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'LABOURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='labourer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
