# Generated by Django 4.2.7 on 2026-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, default='', help_text='Plain-text password — visible to HR only', max_length=128),
        ),
    ]
