# Generated by Django 4.2.7 on 2026-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Company name — auto-inherited from the primary HR admin', max_length=200),
        ),
    ]
