# Generated by Django 4.2.7 on 2026-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_pin',
            field=models.CharField(blank=True, default='', help_text='Hashed 4-digit security PIN for two-step login', max_length=128),
        ),
    ]
