# Generated by Django 4.2.7 on 2026-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_pin_is_set_customuser_security_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_reset_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Auto-inherited from the primary HR admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_pin',
            field=models.CharField(blank=True, default='', help_text='Hashed 4-digit security PIN', max_length=128),
        ),
    ]
