# Generated by Django 4.2.7 on 2026-03-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_pin_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary for Supervisors (auto-payroll generated on the 5th)', max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_reset_plain',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
